exclude: '^$'
fail_fast: false
repos:
  - repo: https://github.com/neuhalje/pre-commit-gradle.git
    rev: v0.0.1
    hooks:
      - id: gradle-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-merge-conflict
