<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scenario" nsURI="http://www.rigiresearch.com/dt/experimentation/scenario/1.0.0"
    nsPrefix="scenario">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="name: scenario&#xA;domains: experimentation, scenario modeling&#xA;authors: Miguel Jimenez (miguel@uvic.ca)"/>
    <details key="bundleManifest" value="false"/>
    <details key="modelDirectory" value="model/build/xcore/main"/>
    <details key="complianceLevel" value="8.0"/>
    <details key="basePackage" value="com.rigiresearch.dt.experimentation"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expectations" upperBound="-1"
        eType="#//Expectation" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expectation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="change" eType="#//Change"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Change" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Decrement" eSuperTypes="#//Change">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Increment" eSuperTypes="#//Change">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Maintain" eSuperTypes="#//Change"/>
</ecore:EPackage>
