<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="monitoring" nsURI="http://www.rigiresearch.com/middleware/monitoring/1.0.0"
    nsPrefix="monitoring">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="name: monitoring&#xA;domains: monitoring, API&#xA;authors: Miguel Jimenez (miguel@uvic.ca)&#xA;description: This metamodel is a representation of the monitors necessary to&#xA; track cloud changes at run-time. These monitors are expected to act as&#xA; historians that will keep asking the cloud provider for the current list of&#xA; computing resources (e.g., virtual machines, disks and networks). Each&#xA; monitor focuses on a specific type of resource, therefore it is given one&#xA; single URL path.&#xA; * TODO optional URL parameters, headers, authentication, produces (XML, JSON)"/>
    <details key="bundleManifest" value="false"/>
    <details key="modelDirectory" value="model/build/xcore/main"/>
    <details key="complianceLevel" value="8.0"/>
    <details key="basePackage" value="com.rigiresearch.middleware.metamodels"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>The root element."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePath" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="https" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authMethods" upperBound="-1"
        eType="#//AuthMethod" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authRequirements" upperBound="-1"
        eType="#//AuthRequirement" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitors" upperBound="-1"
        eType="#//Monitor" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthMethod" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>API Authentication method."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApiKeyAuth" eSuperTypes="#//AuthMethod">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>API authentication based on an API key."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//LocatedProperty"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicAuth" eSuperTypes="#//AuthMethod">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>API authentication based on a base64 encoded string containing a username&#xA;and password in the form username:password. The encoded string must be&#xA;included in the request header as &lt;code>Authorization&lt;/code>, preceded by the&#xA;word Basic. For example: Authorization: Basic X, where X is the encoded&#xA;value."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Oauth2Auth" eSuperTypes="#//AuthMethod">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>API authentication based on Oauth2."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorizationUrl" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flow" unique="false" eType="#//Oauth2Flow"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scopes" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenUrl" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthRequirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>API authentication requires."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scopes" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//AuthMethod"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Monitor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A polling monitor associated with a specific data model and an endpoint&#xA;that returns the instances of the data model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//Path" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//Schema"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rate" eType="#//CronExpression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A GET HTTP path with parameters."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//LocatedProperty" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authRequirements" upperBound="-1"
        eType="#//AuthRequirement" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A typed property."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//DataType"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocatedProperty" eSuperTypes="#//Property">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A property located at a specific location."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" unique="false"
        eType="#//PropertyLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeProperty" eSuperTypes="#//Property">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A composite property to represent arrays and objects."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CronExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A Unix-like cron expression."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A primitive data type."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema" eSuperTypes="#//DataType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A composite data type."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//DataType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>An array data type."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtype" eType="#//DataType"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>Possible property types based on the OpenAPI specification&#xA;(cf. JSONDataType)."/>
    </eAnnotations>
    <eLiterals name="ARRAY" literal="array"/>
    <eLiterals name="BOOLEAN" value="1" literal="boolean"/>
    <eLiterals name="FILE" value="2" literal="file"/>
    <eLiterals name="INTEGER" value="3" literal="integer"/>
    <eLiterals name="NULL" value="4" literal="null"/>
    <eLiterals name="NUMBER" value="5" literal="number"/>
    <eLiterals name="OBJECT" value="6" literal="object"/>
    <eLiterals name="STRING" value="7" literal="string"/>
    <eLiterals name="UNSPECIFIED" value="8" literal="unspecified"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyLocation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>The location of a located property. This enum is based on the OpenAPI&#xA;specification (cf. ParameterLocation). However, as the monitoring paths are&#xA;only of type GET, the BODY constant is not used."/>
    </eAnnotations>
    <eLiterals name="BODY" literal="body"/>
    <eLiterals name="FORM_DATA" value="1" literal="formData"/>
    <eLiterals name="HEADER" value="2" literal="header"/>
    <eLiterals name="PATH" value="3" literal="path"/>
    <eLiterals name="QUERY" value="4" literal="query"/>
    <eLiterals name="UNSPECIFIED" value="5" literal="unspecified"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Oauth2Flow">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>Oauth2 flow types according to the OpenAPI v2 specification."/>
    </eAnnotations>
    <eLiterals name="ACCESS_CODE" literal="accessCode"/>
    <eLiterals name="APPLICATION" value="1" literal="application"/>
    <eLiterals name="IMPLICIT" value="2" literal="implicit"/>
    <eLiterals name="PASSWORD" value="3" literal="password"/>
  </eClassifiers>
</ecore:EPackage>
